version: '3.1'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql

networks: 
  default:
    external: 
      name: ${DOCKER_NETWORK}